version: '2.0'
services:
  mistral:
    image: zjuuu/mistral-frontend:0.1
    expose:
      - port: 80
        as: 80
        accept:
          - chat.akash.network
        to:
          - global: true
profiles:
  compute:
    mistral:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 1Gi
        storage:
          - size: 1Gi
  placement:
    akash:
      attributes:
        host: akash
      pricing:
        mistral:
          denom: uakt
          amount: 10000
deployment:
  mistral:
    akash:
      profile: mistral
      count: 1
